### ISSUE TITLE
Menu with Login module disappear!

### ISSUE THREAD

**Issue by ddpneu** [t3framework/t3#399]
Hello, 
I have a big problem with Megamenu which disappear after clicking in the text area in module.
Please see the attached video. 
Could you please help me to fix it?
It should be still open until I move with mouse out of the menu module.
Thank you.

![_menu](https://cloud.githubusercontent.com/assets/7712105/8233797/767e9942-15d8-11e5-9f4d-e7329a584907.gif)

**Comment by ddpneu** [comment]
Hello, 
please, does somebody know where is the problem? It is a big problem for our customers.
Thank you.

**Comment by khanhlh** [comment]
The problem is fixed on commit https://github.com/t3framework/t3/commit/971014820a1b1df70108c962d3b8742da436b6da. Please apply the fix and check if it works on your end.

**Comment by betteryouthanme** [comment]
thanks a lot for this fix, works like a charm ;)

**Comment by ddpneu** [comment]
I´m so sorry for my late response. I upload the new menu.js but it doesn´t work for me, Could you please help me why it that still happening?

**Comment by betteryouthanme** [comment]
Did you delete cache? (ctrl+f5)

**Comment by ddpneu** [comment]
yes. I deleted cache in joomla also. I tryed now different browser (I´m using firefox so I tryed Chrome) and still the same . I have no idea why it doesn´t work:-(

**Comment by betteryouthanme** [comment]
then i don't know. For me it works with Purity III.

**Comment by khanhlh** [comment]
The issue is solved already. Please check.
